### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [msecher/PreCourlis#33]
# Problem

Please add a small English description of what the plugin does

**Comment by NyakudyaA** [comment]
ping @arnaud-morvan

**Comment by arnaud-morvan** [comment]
@NyakudyaA : thanks for raising this, I've added english description and about sections, and re-published on https://plugins.qgis.org/plugins/PreCourlis/.
Regards

**Comment by arnaud-morvan** [comment]
Plugin is approved, I close this issue.
